Sercon_14062020/Proyecto_PAA/Models/Ticket.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Proyecto_PAA.Models
{
    public class Ticket
    {
        [Key]
        public int id { get; set; }
        [Required]
        public DateTime FechaGeneracion { get; set; }
        [Required]
        public int idEstado { get; set; }
        [ForeignKey("idEstado")]
        public Estado Estado { get; set; }
        [Required]
        public int idRequerimiento { get; set; }
        [ForeignKey("idRequerimiento")]
        public Requerimiento Requerimiento { get; set; }
        [Required]
        public int PrioridadId { get; set; }
        [ForeignKey("PrioridadId")]
        public Prioridad Prioridad { get; set; }
        [Required]
        public int UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; }
        [Required]
        [MaxLength(8000)]
        public string Descripcion { get; set; }
        [MaxLength(8000)]
        public string Solucion { get; set; }
        

    }
}

Sercon_14062020/Proyecto_PAA/ViewModels/TicketViewModel.cs
using Proyecto_PAA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyecto_PAA.ViewModels
{
    public class TicketViewModel
    {
        public Ticket Ticket { get; set; }

        public List<Ticket> Tickets { get; set; }
        public List<Estado> Estados { get; set; }
        public List<Requerimiento> Requerimientos { get; set; }
        public List<Prioridad> Prioridades { get; set; }
        public List<User> Users { get; set; }
        public List<Establecimiento> Establecimientos { get; set; }
        public List<UserRole> UserRoles { get; set; }
        public List<Role> Roles { get; set; }

    }
}

Sercon_14062020/Proyecto_PAA/Controllers/TicketController.cs
using Proyecto_PAA.Models;
using Proyecto_PAA.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_PAA.Controllers
{
    public class TicketController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();
        // GET: Ticket
        public ActionResult Index()
        {
            var listado = context.Tickets;
            return View(listado);
        }
        [HttpGet]
        public ActionResult Nuevo()
        {
            var viewmodel = new TicketViewModel();
            viewmodel.Requerimientos = context.Requerimientos.ToList();
            viewmodel.Estados = context.Estados.ToList();
            viewmodel.Users = context.Users.ToList();
            viewmodel.Prioridades = context.Prioridades.ToList();
            return View(viewmodel);
        }
        [HttpPost]
        public ActionResult Nuevo(Ticket ticket)
        {
            context.Tickets.Add(ticket);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
    
}

Sercon_14062020/Proyecto_PAA/Views/Ticket/Index.cshtml
@model IEnumerable<Ticket>
@{
    ViewBag.Title = "Index";
}
<h2>
    <a style="float:right;color:green" href="@Url.Action("Nuevo","Ticket")">
        <i class="fas fa-plus-circle"></i>
    </a>
    Listado de Tickets
</h2>
<hr />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Fecha</th>
            <th>Estado</th>
            <th>Usuario</th>
            <th>Requerimiento</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ticket in Model)
        {
            <tr>
                <td>@ticket.id</td>
                <td>@ticket.FechaGeneracion</td>
                <td>@ticket.Estado.Nombre</td>
                <td>@ticket.User.FullName</td>
                <td>@ticket.Requerimiento.RequerimientoTipo</td>
                <td style="width:50px">
                    <a href="@Url.Action("Detalle","Ticket", new { id=ticket.id})" title="Ver Detalle" style="color:blue"><i class="far fa-eye"></i></a>
                    <a href="@Url.Action("Actualizar","Ticket", new { id=ticket.id})" title="Actualizar" style="color:green"><i class="fas fa-edit"></i></a>
                    <a href="javascript:void(0)" onclick="getID(@ticket.id)" data-toggle="modal" data-target="#exampleModal" title="Eliminar" style="color:red"> <i class="far fa-trash-alt"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Está seguro de eliminar el Ticket?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="deleteTicket()">Si, estoy seguro</button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" value="" id="idTicket" />
<script>
    function deleteTicket() {
        let url = '@Url.Action("Eliminar","Ticket")'
        url = url + '/' + $("#idTicket").val();
        window.location.href = url;
    }
    function getID(id) {
        $("#idTicket").val(id);

    }
</script>

Sercon_14062020/Proyecto_PAA/Views/Ticket/Nuevo.cshtml
@model TicketViewModel
@{
                /**/

                ViewBag.Title = "Nuevo";
}

<h2>
    <a style="float:right;color:green" href="@Url.Action("Index","Ticket")">
        <i class="fas fa-arrow-circle-left"></i>
    </a>
    Nuevo Ticket
</h2>
<hr />

@using (Html.BeginForm("Nuevo", "Ticket", FormMethod.Post))
{
    <div class="form-group">
        <label>Fecha Generacion</label>
        @Html.TextBoxFor(m => m.Ticket.FechaGeneracion, new { @class = "form-control", @required = "required", @type = "date" })
    </div>
    <div class="form-group">
        <label>Estado</label>
        <select name="Ticket.IdEstado" class="form-control" required>
            <option value="">Seleccione</option>
            @foreach (var estado in Model.Estados)
            {
                <option value="@estado.id">@estado.Nombre</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Usuario</label>
        <select name="Ticket.IdUsuario" class="form-control" required>
            <option value="">Seleccione</option>
            @foreach (var usuario in Model.Users)
            {
                <option value="@usuario.UserId">@usuario.FullName</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Descripción</label>
        @Html.TextAreaFor(m => m.Ticket.Descripcion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Tipo Requerimiento</label>
        <select name="Ticket.IdRequerimiento" class="form-control" required>
            <option value="">Seleccione</option>
            @foreach (var requerimiento in Model.Requerimientos)
            {
                <option value="@requerimiento.RequerimientoId">@requerimiento.RequerimientoTipo</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Prioridad</label>
        <select name="Ticket.IdPrioridad" class="form-control" required>
            <option value="">Seleccione</option>
            @foreach (var prioridad in Model.Prioridades)
            {
                <option value="@prioridad.PrioridadId">@prioridad.PrioridadTipo</option>
            }
        </select>
    </div>
    <div>
        <input type="submit" value="Guardar" class="btn btn-success" />
    </div>

}